<a href="https://colab.research.google.com/github/PacktPublishing/Modern-Computer-Vision-with-PyTorch-2E/blob/main/Chapter02/Initializing_a_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch
x = torch.tensor([[1,2]])
y = torch.tensor([[1],[2]])

In [7]:
print(x.shape)
# torch.Size([1,2]) # one entity of two items
print(y.shape)
# torch.Size([2,1]) # two entities of one item each
print(x.dtype)
# torch.int64

torch.Size([1, 2])
torch.Size([2, 1])
torch.int64


In [8]:
x = torch.tensor([False, 1, 2.0])
""" NOTE: Boolean values translate to binary values (0,1 : False,True)
    All generalize to be floating point numbers due to mixed types """

#NOTE: If all integers --> int64; if mixed or contains floats --> float32; complex is complex :D

print(x)
# tensor([0., 1., 2.])

print(x.dtype)

tensor([0., 1., 2.])
torch.float32


In [9]:
torch.zeros((3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
torch.ones((3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
torch.randint(low=0, high=10, size=(3,4))

tensor([[2, 2, 5, 4],
        [4, 3, 1, 3],
        [6, 1, 9, 6]])

In [12]:
torch.rand(3, 4)

tensor([[0.1115, 0.4331, 0.3378, 0.3662],
        [0.1756, 0.3560, 0.7802, 0.3418],
        [0.5384, 0.0973, 0.6719, 0.1570]])

In [13]:
torch.randn((3,4))

tensor([[ 0.7444,  0.6333, -1.2549, -0.4642],
        [ 0.7421, -1.0488,  0.7003,  1.7534],
        [ 0.3551, -2.6822, -1.1395,  3.1629]])

In [14]:
import numpy as np
x = np.array([[10,20,30],[2,3,4]])
y = torch.tensor(x)
print(type(x), type(y))

<class 'numpy.ndarray'> <class 'torch.Tensor'>
